export const DECREMENT_MAIN_COUNTER = 'DECREMENT_MAIN_COUNTER'
export const INCREMENT_MAIN_COUNTER = 'INCREMENT_MAIN_COUNTER'

export const CREATE_KEY_PAIR = 'CREATE_KEY_PAIR'

export const CREATE_USER = 'CREATE_USER'
export const READ_USER = 'READ_USER'
export const READ_USERS = 'READ_USERS'
export const UPDATE_USER = 'UPDATE_USER'
export const DELETE_USER = 'DELETE_USER'
